### ISSUE TITLE
Add support for extended COLLECT

### ISSUE THREAD

**Issue by pluma** [arangodb/aqbjs#10]
Via @jsteemann:

COLLECT can now have OPTIONS:

* no OPTIONS:

 `FOR i IN 1..10 COLLECT value = i RETURN i`

* with OPTIONS:

 `FOR i IN 1..10 COLLECT value = i OPTIONS { method: "hash" } RETURN value`

* with INTO and OPTIONS:

 `FOR i IN 1..10 COLLECT value = i INTO g OPTIONS { method: "hash" } RETURN { value: value, g: g }`

* with COUNT INTO and OPTIONS:

 `FOR i IN 1..10 COLLECT value = i WITH COUNT INTO length OPTIONS { method: "hash" } RETURN { value: value, length: length }`

* without definitions but with COUNT INTO:

 `FOR i IN 1..10 COLLECT WITH COUNT INTO length RETURN length`

**Comment by pluma** [comment]
I'll need some input from @jsteemann for the full range of valid syntax. It's quite a bit more complex than the original BNF indicated.

**Comment by jsteemann** [comment]
@pluma : what do you need to know?

**Comment by pluma** [comment]
@jsteemann let's discuss this when I'm on site tomorrow. I'm not fully sure I understand all the productive rules for the COLLECT statement, i.e. which combinations are possible and where each particle can go.

**Comment by jsteemann** [comment]
@pluma: aye aye

**Comment by pluma** [comment]
Fixed in master.
