### ISSUE TITLE
Support graph operations

### ISSUE THREAD

**Issue by jrsnyder** [arangodb/aqbjs#12]
https://docs.arangodb.com/Aql/GraphOperations.html

**Comment by pluma** [comment]
The graph operations are AQL functions. Like all AQL functions they should all be available as methods of the query builder, e.g.

```js
var qb = require('aqb');
var aql = qb.GRAPH_EDGES('graphName', 'vertexExample', {});
```

If any of the parameters aren't handled correctly or any methods are missing, we can update them at any time. You can also use arbitrary AQL functions with the `fn` method:

```js
aql = qb.fn('GRAPH_EDGES')('graphName', 'vertexExample', {});
```

**Comment by jrsnyder** [comment]
Ok, I didn't understand all the AQL functions were available like that.  Thank you.  Should have read more carefully...
