### ISSUE TITLE
AQB support collection in bind variables?

### ISSUE THREAD

**Issue by mrbatista** [arangodb/aqbjs#14]
If execute this query:
````javascript
aql = qb.insert('@data').in('@@collection').returnNew('inserted')
 bindVars = {
 data: data, 
 collection: 'SimpleModel'
}
````
Query is converted into: 
`INSERT @data INTO @@collection LET inserted = NEW RETURN inserted`
but when execute a query I receive: 
`ArangoError: no value specified for declared bind parameter '@collection' (while parsing)]
  message: 'no value specified for declared bind parameter \'@collection\' (while parsing)',
  errorNum: 1551,
  code: 500`

If change query with:
```javascript
aql = qb.insert('@data').in('SimpleModel').returnNew('inserted')
 bindVars = {
 data: data
}
```
this works.

**Comment by pluma** [comment]
Try this:
```js
aql = qb.insert('@data').in('@@collection').returnNew('inserted')
bindVars = {
  data: data, 
  '@collection': 'SimpleModel'
}
```

Collections are different. :)

**Comment by mrbatista** [comment]
works! Thanks!
