### ISSUE TITLE
Data modification queries should support RETURN, LET, etc

### ISSUE THREAD

**Issue by pluma** [arangodb/aqbjs#15]
Currently they only support returnNew and/or returnOld. Sometimes you don't want to use those and instead return something else.

**Comment by mrbatista** [comment]
Please add support for `RETURN`.
For example is not possible to write this query:
 
`UPSERT {ip: "192.168.173.13"}
INSERT {ip: "192.168.173.13", name: "flittard"}
UPDATE {} 
IN User
RETURN {doc: NEW, isNewInstance: OLD ? false : true }`
