### ISSUE TITLE
Should `NOT IN` statement also be supported by aqbjs?

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/aqbjs#17]
Hi, 

I found it's missing in the aqbjs. Maybe it could also be done by combining with `Negative`.

Bg,
Kevin

**Comment by pluma** [comment]
Is there any difference between `x NOT IN y` and `!(x IN y)`? Otherwise you could just use `qb.not(qb.in(x, y))` for the meantime. I agree that having a shorthand would be handy, though.
