### ISSUE TITLE
Array filter query

### ISSUE THREAD

**Issue by GlurG** [arangodb/aqbjs#22]
How do I create the following query using the query builder? (example taken from the docs) https://docs.arangodb.com/3.0.10/AQL/Advanced/ArrayOperators.html)

```
FOR u IN users
    RETURN {
        name: u.name,
        friends: u.friends[* FILTER CONTAINS(CURRENT.name, "a") AND CURRENT.age > 40
            LIMIT 2
            RETURN CONCAT(CURRENT.name, " is ", CURRENT.age)
        ]
    }
```

**Comment by Simran-B** [comment]
@pluma correct me if I'm wrong, but AFAIK there is no direct support for array operators in aqb. While you could use a [raw expression](https://github.com/arangodb/aqbjs#raw-expression) for that part of the query, it is discouraged (injection attacks) and it makes the code harder to read:

```js
aqb.for('u').in('users')
  .return({
    name: aqb.get('u', '"name"'),
    friends: aqb.get('u', '"friends"').get(aqb.expr('* ' + aqb.filter(
      aqb.CONTAINS(aqb.get('CURRENT', '"name"'), aqb.str('a'))
      .and(aqb.gt(aqb.get('CURRENT','"age"'), 40)))
    .limit(2)
    .return(aqb.CONCAT(aqb.get('CURRENT','"name"'),
      aqb.str(' is '), aqb.get('CURRENT','"age"'))).toAQL()))
  }).toAQL()
```

Unless there's a reason why you really have to generate a query with aqb, using the `aql` string template is preferred since 3.0:

```js
const aql = require('arangojs').aql;

db._query(aql`
    FOR entry IN ${coll}
    RETURN entry._key
`);
```

If you really want to stick with aqb, you can translate the query to the more verbose form without array operators:

```js
FOR u IN users
    RETURN {
        name: u.name,
        friends: (FOR f IN u.friends
            FILTER CONTAINS(f.name, "a") AND f.age > 40
            LIMIT 2
            RETURN CONCAT(f.name, " is ", f.age)
        )
    }
```

```js
aqb.for('u').in('users')
  .return({
    name: aqb.get('u', '"name"'),
    friends: aqb.for('f').in(aqb.get('u', '"friends"'))
      .filter(aqb.and(aqb.CONTAINS(aqb.get('f', '"name"'), aqb.str('a')),
        (aqb.gt(aqb.get('f','"age"'),40))))
      .limit(2)
      .return(aqb.CONCAT(aqb.get('f','"name"'), aqb.str(' is '), aqb.get('f','"age"')))
  }).toAQL()
```

**Comment by pluma** [comment]
That's right. AQB is actually lagging behind ArangoDB a bit at this point.

If you want to write arbitrary AQL queries in ArangoDB (e.g. with Foxx or in transactions) or in JavaScript using the [arangojs](https://github.com/arangodb/arangojs) driver the best option is to use the `aql` template handler:

```js
db._query(aql`
    FOR u IN users
    RETURN {
        name: u.name,
        friends: (FOR f IN u.friends
            FILTER CONTAINS(f.name, "a") AND f.age > 40
            LIMIT 2
            RETURN CONCAT(f.name, " is ", f.age)
        )
    }
`)
```

ES6 template strings (supported in ArangoDB and newer versions of Node as well as in newer browsers or via Babel) can span multiple lines and the `aql` template handler correctly interpolates variables as AQL bind parameters to avoid injection attacks:

```js
var someNumber = 42
var someCollection = db.myCollection
db._query(aql`
    FOR doc IN ${someCollection}
    FILTER doc.number > ${someNumber}
    RETURN doc
`)
```

If you need to inject AQL snippets you can do that by wrapping them in objects with a `toAQL` method (to avoid accidental injections from client-side data):

```js
var myFilter = 'FILTER doc.number > 23`
db._query(aql`
    FOR doc IN myCollection
    ${{toAQL: () => myFilter}}
    RETURN doc
`)
```

This also works with AQB objects, which always define a `toAQL` method.
