### ISSUE TITLE
ArangoError: AQL: syntax error, unexpected end of query string

### ISSUE THREAD

**Issue by CanRau** [arangodb/aqbjs#26]
can't get this to work

````
let query = aqb
   .for('doc')
   .in(aqb.FULLTEXT(collection, aqb.str(field), aqb.str(query)))

if (limit) query.limit(limit)

query.return('doc')
````

while this does work

````
let query = aqb
   .for('doc')
   .in(aqb.FULLTEXT(collection, aqb.str(field), aqb.str(query)))
   .limit(limit)
   .return('doc')
````

**Comment by pluma** [comment]
The query builder is no longer being actively maintained.

I recommend using the `aql` template handler instead:

https://docs.arangodb.com/3.2/Manual/Appendix/JavaScriptModules/ArangoDB.html#the-aql-template-string-handler

https://github.com/arangodb/arangojs#aql

**Comment by CanRau** [comment]
took me a little longer to reply sorry for that

okay, thought aqb is still a nice option for more complex dynamic queries.. :)
