### ISSUE TITLE
Add COLLECT ... COUNT

### ISSUE THREAD

**Issue by pluma** [arangodb/aqbjs#4]
See https://github.com/triAGENS/ArangoDB/commit/19a69067cde120ad33ffc62ecd35d45341419992

**Comment by samuelgoldenbaum** [comment]
How would be write the following AQL equivalent:

FOR m IN members
FILTER m.email == 'darth@empire.galaxy'
COLLECT WITH COUNT INTO length
RETURN length

**Comment by pluma** [comment]
Good catch. See #10.
