### ISSUE TITLE
String escaping not well supported

### ISSUE THREAD

**Issue by CoDEmanX** [arangodb/aqbjs#5]
Characters like `-` (minus) in collection names are allowed, but need to be escaped in AQL. aqb does not auto-magically escape them, nor does it accept collection names manually escaped with `` `backticks` ``:

    // fail
    aqb.for("doc").in("TBL-MAIN_DSO").return("doc").toAQL()
    aqb.for("doc").in("`TBL-MAIN_DSO`").return("doc").toAQL()

    // works, but it's complicated
    aqb.for("doc").in(aqb.expr("`TBL-MAIN_DSO`")).return("doc").toAQL()

    // pure AQL
    FOR doc IN `TBL-MAIN_DSO` RETURN doc

**Comment by pluma** [comment]
Confirmed: currently hyphen-minus is accepted but not escaped properly.
