### ISSUE TITLE
Property starts with `@` is not allowed

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/aqbjs#6]
Hi,

I tried to build the following query which is allowed in arangoDB

```
FOR node IN @@collection \
     FILTER node.`@id` == @iri \
     RETURN node \
```

```js
qb.for('u').in('users').limit(qb.eq('u.`@id`', qb.str('xxx'))).return('u');
```

Unfortunately, aqb returns an error. It does not work in aqb.

**Comment by jsteemann** [comment]
Throws:
```
JavaScript exception in file './js/node/node_modules/aqb/types.js' at 255,11: AqlError: Not a valid simple reference: u.`@id`
```

I think the regex in aqb/types.js:259 does not cover all cases:
```js
SimpleReference.re = /^@{0,2}[_a-z][_0-9a-z]*(\.[_a-z][_0-9a-z]*|\[\*\])*$/i;
```
It won't let the following valid expressions pass:
```
a.@bindVariable  // using a bind parameter here
a.`@quotedName`  // using attribute name "@quotedName"
a.`another quoted name`   // using attribute name with whitespace
a.`mötörheäd`  // umlauts, other non-ASCII characters are possible here, too
```
Basically, anything that's contained inside backticks can be allowed.
Additionally, a bind variable can be used directly after the dot.

**Comment by pluma** [comment]
So the backticks can even be used for dot property syntax? Interesting. Going by the BNF grammar I thought it'd behave like JS where problematic names need to be used as quoted strings with the bracket property syntax: `a["mötörheäd"]` or `a[@someVar]`.

**Comment by jsteemann** [comment]
No, the backtick syntax is used mostly to use attribute names that would conflict with other reserved things, such as keywords or bind parameters, e.g.
```
FOR doc IN collection
  FILTER doc.`filter` == 1 && doc.`@id` == 9
 RETURN doc
```
Though in the above examples, `doc["filter"]` and `doc["@id"]` should also work.

**Comment by kevinprotoss** [comment]
Thx for your reply. I agree with @jsteemann , all string values in the backslash should be considered as an attribute name.
